curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Knowit Muchachos", "player1":"Rune Hansen", "player2":"Rune Hallesen", "player3":"Rune Øygarden"}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Knowit Ruggabaga", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Evry Ford Mustang 1967", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Sixty Barricade", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Frende Fussers", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Evry object reference not set to an instance of an object", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Bouvet Sparebanken Vest", "player1":"Torbjørn Marø", "player2":"Robert Hopland", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Knowit daRuud Rommstorm", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Escali Giants", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"GexCon Gaucho Noruega", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Sixty Bye", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Knowit Askøy Kommune Oldboys", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Knowit Frende Champs", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Sixty Kill", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Sixty Stril", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"Sparebanken Vest i siste liten", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"aaaaaa", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"bbbbbbb", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"cccccc", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"ddddddddddddd", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"eeeeeeeeeeeeee", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"ffffffffffff", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"gggggggggggg", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"hhhhhhhhhhhhhhh", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"iiiiiiiiiiiiiii", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"jjjjjjjjjjjjjjj", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"kkkkkkkkkkkkkkkkkkkk", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"lllllllllllllllll", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"mmmmmmmmmmmmmmm", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"nnnnnnnnnnnnnn", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"ooooooooooooo", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"ppppppppppppppp", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"qqqqqqqqqqqqqq", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"rrrrr", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"ssssssssssssss", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"ttttttttttttttt", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"uuuuuuuuuuuuuuuuu", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"vvvvvvvvvvvvvvv", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"wwwwwwwwwwwwwww", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"xxxxxxxxxxxxxxxx", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"yyyyyyyyyyyyyyyyy", "player1":"", "player2":"", "player3":""}'
curl http://localhost:1323/tournaments/1/teams -H 'Content-Type: application/json' -d '{"name":"zzzzzzzzzzzzzzz", "player1":"", "player2":"", "player3":""}'
